apiVersion: apps/v1
kind: Deployment
metadata:
  name: client
  labels:
    app: mysite
    tier: client
spec:
  replicas: 3
  selector:
    matchLabels:
      app: mysite
      tier: client
  template:
    metadata:
      labels:
        app: mysite
        tier: client
    spec:
      containers:
      - name: client
        image: gcr.io/{my-project-id}/my-client:0.1
        ports:
        - containerPort: 3010